# Generated by Django 5.2.15 on 2026-06-07 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cin', models.CharField(max_length=12, unique=True, verbose_name='Numéro de CIN')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom(s)')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=15, verbose_name='Numéro de téléphone')),
                ('photo_identite', models.ImageField(upload_to='photos_identite/', verbose_name="Photo d'identité")),
                ('empreinte_digitale', models.ImageField(upload_to='empreintes/', verbose_name='Fichier image Empreinte')),
                ('scan_recto', models.ImageField(upload_to='scans_recto/', verbose_name='Fichier image Recto')),
                ('scan_verso', models.ImageField(upload_to='scans_verso/', verbose_name='Fichier image Verso')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('APPROUVE', 'Approuvé (À imprimer)'), ('REJETE', 'En attente de modification'), ('IMPRIME', 'Imprimé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut du dossier')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépôt')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cin_saisies', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cin_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de CIN',
                'verbose_name_plural': 'Demandes de CIN',
                'ordering': ['-date_creation'],
            },
        ),
    ]
