# Generated by Django 5.2.15 on 2026-06-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandecin',
            name='empreinte_digitale',
        ),
    ]
