# Generated by Django 5.2.15 on 2026-06-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cin', '0002_remove_demandecin_empreinte_digitale'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecin',
            name='est_duplicata',
            field=models.BooleanField(default=False, verbose_name="C'est un duplicata"),
        ),
        migrations.AddField(
            model_name='demandecin',
            name='nom_complet_mere',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom complet de la mère'),
        ),
        migrations.AddField(
            model_name='demandecin',
            name='nom_complet_pere',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom complet du père'),
        ),
    ]
