# Generated by Django 5.2.15 on 2026-06-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cin', '0003_demandecin_est_duplicata_demandecin_nom_complet_mere_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandecin',
            old_name='nom_complet_mere',
            new_name='nom_mere',
        ),
        migrations.RenameField(
            model_name='demandecin',
            old_name='nom_complet_pere',
            new_name='nom_pere',
        ),
        migrations.RemoveField(
            model_name='demandecin',
            name='est_duplicata',
        ),
        migrations.AddField(
            model_name='demandecin',
            name='duplicata',
            field=models.BooleanField(default=False, verbose_name='Duplicata'),
        ),
    ]
